"""
Django settings for DjangoBlog project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 123
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qnf(==ufo33b8=f8cyyzq=i5kj9276idj!%a!gh_woumb5*ezk'

# SECURITY WARNING: don't run with debug turned on in production!
# 在生产环境的时候需要把DEBUG改为 false
# DEBUG = False
DEBUG = True

# 一旦把DEBUG改为False,就需要添加HOST,生产环境的时候需要向[]中添加域名或者ip地址
# 目前为了测试,暂时填写*
# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
    # 添加网站的站点地图
    'django.contrib.sitemaps',
    # 使用Django自带的评论插件
    'django.contrib.sites',  # 添加站点的插件
    'django_comments',  # 添加评论的插件
]

# 设置站点的值为1,Django支持多个站点运行,目前我们只使用一个站点
# 使用Django的插件要求制定站点的id
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoBlog.wsgi.application'


"""
# 这两行代码一定要写在这个地方 如果在__init__()文件中进行了引入的话,此处就没必要进行配置了
import pymysql
pymysql.install_as_MySQLdb()
"""
DATABASES = {
    'default': {
        # 让django使用mysql数据库
        'ENGINE': 'django.db.backends.mysql',
        # 指定数据库的名字
        'NAME': 'pythonblog',
        # 指定数据的相关信息
        'USER': 'root',
        'PASSWORD': 'mysql',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# 静态文件的跟目录
STATIC_ROOT = os.path.join(BASE_DIR, 'all_static_files')

# 多媒体文件的根目录,博客的文章配图上传到该目录下面
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace("\\", "/")
MEDIA_URL = '/media/'

# 微博登录的账号和密码
CLIENT_ID = 3
APP_SECRET = '6b3f08a3afde59a0828a99678d6f1020'
